### ISSUE TITLE
Efficient memory management for HashIndex

### ISSUE THREAD

**Issue by meyerdan** [zeebe-io/zb-util#24]
Currently hashIndex manages it's data in the filesystem. To batch writes and buffer reads to fs, a buffer cache is used.

We should rewrite the index's memory management so that all data is kept in memory.

**Comment by ThorbenLindhauer** [comment]
Hi @menski, what's the purpose of commit https://github.com/zeebe-io/zb-util/commit/68964cd5b574c21530e6afa5eac2d6ff14be93cc, see https://github.com/zeebe-io/zb-util/issues/24#issuecomment-314922879?

Does it ensure that 

* A zb map can be restored from an input stream even if the stream throws IO exceptions (that's how I understood the test classes/methods at first)?
* A zb map can be restored from an input stream even when the stream's `#read` methods return less bytes than requested (that's what I understand is currently tested)
* something else?

**Comment by menski** [comment]
@ThorbenLindhauer the commit was indented to at least handle situations where the reader was not able to read all the bytes at once. In this old code the return of `inputStream#read` was ignored and then a `copyMemory` was called with `readLength` where the `read` call could return a different value.

```java
inputStream.read(buffer, 0, readLength);
UNSAFE.copyMemory(buffer, ARRAY_BASE_OFFSET, null, addr + offset, readLength); 
```

Does this answer you question?

**Comment by ThorbenLindhauer** [comment]
Yes, thanks.
