### ISSUE TITLE
Bytes2BytesZbMap

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zb-util#35]
Map that has byte array keys and values.

**Comment by Zelldon** [comment]
# Review
## Tests
 I think we should also test the put/remove methods if the key or specially for the put if the value is to long. Like you do it with

```java
+    @Test
 +    public void shouldRejectIfKeyTooLong()
 +    {
 +        // then
 +        expection.expect(IllegalArgumentException.class);
 +
 +        // when
 +        map.get(new byte[65], value);
 +    }
```

Created a new issue https://github.com/zeebe-io/zb-util/issues/37 to add the missing test cases for the other implementations.
