### ISSUE TITLE
ZbMap: OPTIMAL_BLOCK_COUNT and OPTIMAL_TABLE_SIZE still needed?

### ISSUE THREAD

**Issue by meyerdan** [zeebe-io/zb-util#40]
This is a question for @Zelldon: do we still need these properties? What is their current purpose?

**Comment by Zelldon** [comment]
Nope I will remove them

**Comment by meyerdan** [comment]
Great, thank you! less config options and fewer knobs to turn.

**Comment by menski** [comment]
Seems that the constants are still used in the log streams module

https://hq2.camunda.com/jenkins/zeebe/job/zb-logstreams-DISTRO-maven-deploy/61/
